version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: grizzly_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: grizzly_user
      POSTGRES_PASSWORD: grizzly_password
      POSTGRES_DB: grizzly_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: 
